#!/bin/bash
#########################################


#########################################
# Variables
#########################################
#
#'set -u' will exit your script if you try to use an uninitialised variable. 
set -u
export LANG=C

prog="$(basename $0)"
target_part=${1:-}

[ -z ${SETCOLOR_SUCCESS:-''} ] && SETCOLOR_SUCCESS="echo -en \\033[1;32m"
[ -z ${SETCOLOR_FAILURE:-''} ] && SETCOLOR_FAILURE="echo -en \\033[1;31m"
[ -z ${SETCOLOR_WARNING:-''} ] && SETCOLOR_WARNING="echo -en \\033[1;33m"
[ -z ${SETCOLOR_NORMAL:-''}  ] && SETCOLOR_NORMAL="echo -en \\033[0;39m"
BOOTUP="color"

#########################################
# Functions
#########################################
#

ERROR() {
    echo -en "\\033[1;31m"
    echo "ERROR: $1"
    echo -en "\\033[1;39m"
    exit 1
}

WARNING() {
    echo -en "\\033[1;33m"
    echo "$1"
}

SUCCESS() {
    echo -en "\\033[1;32m"
    echo "$1"
}

INFO() {
    echo -en "\\033[1;39m"
    echo "$1"
}

USAGE() {
   echo "To make the device bootable with syslinux"
   echo "Usage: $prog <partition_device>"
   echo "Note:"
   echo "  Device assignment priority: Partition name > UUID > LABEL (if not only one NAME-TYPE is assigned)"
   echo "Example: $prog /dev/sdg1" 
   echo "To make \"/dev/sdg1\" bootable on GNU/Linux:"
}

# Check if root or not
check_if_root() {
   if [ ! "$UID" = "0" ]; then
     ERROR "You need to run this script '$prog' as root."
   fi
}

check_if_exist() {
    if ! type $1 &>/dev/null; then
      ERROR "Program '$1' was not found on this GNU/Linux system. Please install it."
    fi
}

get_diskname() {
  local disk=${1#/dev/*}

  if [ -n "$disk" ]; then
    echo "$disk" | sed -e 's/^\([^0-9]*\)[0-9]*$/\1/g' \
                       -e 's/^\(.*[0-9]\{1,\}\)p[0-9]\{1,\}$/\1/g'
  fi
} # end of get_diskname
#
get_part_number() {
  local disk=${1#/dev/*}
  local num=""

  if [ -n "$disk" ]; then
    num=$(echo "$disk" | sed -e 's/^[^0-9]*\([0-9]*\)$/\1/g' \
                             -e 's/^.*[0-9]\{1,\}\(p[0-9]\{1,\}\)$/\1/g')
  fi

  echo $num
} # end of get_part_number
#

#
#########################################
# Main
#########################################
#

check_if_root
check_if_exist syslinux
check_if_exist parted
check_if_exist blkid

# Check if device is defined in parameter
if [ -z "$target_part" ]
then
  USAGE
  ERROR "No target partition could be determined"
fi
# Make sure target_part is partition device name, not disk device name
if [ -z "$(echo $target_part | grep -iE "/dev/[hsu][bd][a-z]+[[:digit:]]+")" ]; then
  ERROR "'$target_part' is NOT a valid partition name"
fi

#
pt_dev="$(basename $target_part)"  # e.g. sdc1
hd_dev="$(get_diskname $target_part)"   # e.g. sdc
target_disk="/dev/$hd_dev"  # e.g. /dev/sdc
pt_dev_no="$(get_part_number $target_part)"  # e.g. 1

# If the destination disk is not MBR partition table (e.g. it's GPT), exit. This program only works for MBR disk.
if [ -z "$(LC_ALL=C parted -s $target_disk print | grep -iE "^Partition Table:" | grep -iE "msdos")" ]; then
  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
  echo "The partition table of $target_disk is not for MBR (Master Boot Record). Its layout is:"
  LC_ALL=C parted -s $target_disk print
  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
  echo "This program is for making a bootable disk with MBR partition table."
  echo "For GPT disk, there is no need to run this program. Just make sure the partition is FAT32 with ID=ef00 and all the files are copied on that. That's all."
  exit 1
fi

#
if ! grep -qEw $pt_dev /proc/partitions; then
  ERROR "$target_part was NOT found in /proc/partitions"
fi

#
echo "This command will install MBR and syslinux bootloader on $target_disk"
echo "--------------------------------------------"
parted -s $target_disk print
echo "--------------------------------------------"
echo "Check if $target_part is a FAT partition"
LC_ALL=C blkid -c /dev/null $target_part | grep -o -E '\<TYPE="[^[:space:]]*"($|[[:space:]]+)' >blkinfo
TYPE=""
. blkinfo
echo "File system of $target_part is $TYPE"
rm blkinfo
case "$TYPE" in
  fat16|fat32|vfat)
     echo "$target_part is a valid FAT file system."
     ;;
#  ntfs|ext[2-4]|btrfs|xfs|ufs|ffs) mode="extlinux";;
  *)                   
     ERROR "$target_part doesn't look like a valid FAT file system."
     ;;
esac

echo "--------------------------------------------"
# 2. Bootable ?
echo "Check if $target_part is bootable"
device_no="$(get_part_number $target_part)"  # e.g. 1
LANG=C parted -s $target_disk print | egrep "^ $device_no .* boot$"
if [ "$?" -eq 0 ]
then
  echo "$target_part is already marked as bootable"
else
  echo "$target_part is not marked as bootable"
  parted -s $target_disk print
  echo "Running: parted -s $target_disk set $device_no boot on"
  parted -s $target_disk set $device_no boot on
fi

# 3. Install MBR
echo "--------------------------------------------"
echo "Installing Master Boot Record on $target_disk"
cat /usr/lib/syslinux/mbr/mbr.bin >$target_disk
if [ "$?" -ne 0 ]; then
  ERROR "Failed to write bootloader into MBR of $target_disk"
fi

# 4. Install Linux system
echo "--------------------------------------------"
mount_point="/mnt"
mount $target_part $mount_point
echo "Copying system files to $target_part"
cp /vmlinuz $mount_point/
cp initrd.img $mount_point/
echo "Running: syslinux --install \"$target_part\""
syslinux --install "$target_part"
echo "--------------------------------------------"
echo "Mounted point of $target_part is $mount_point"
ls -l $mount_point
umount $target_part
