#!/bin/sh
version="$(uname -r)"
# Media target may change
target="/media/pba/PBA"

if [ ! -d $target ]
then
  echo "ERROR: unknown target directory"
  exit 1
fi
# Let's go
set -x
cd initrd
mkdir lib/firmware
cp    /lib/firmware/phanfw.bin lib/firmware/
cp -r /lib/firmware/$version   lib/firmware/
mkdir lib/modules
mkdir lib/modules/$version
cp    /lib/modules/$version/modules.* lib/modules/$version/
cp -r /lib/modules/$version/kernel    lib/modules/$version/

find . | cpio --quiet -o -H newc | xz -c -9 --check=crc32 >../initrd.img

rm -r lib/firmware
rm -r lib/modules
cd ..
cp /vmlinuz   $target/
mv initrd.img $target/
